In [1]:
import numpy
word_alcohol = numpy.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str)
print(type(word_alcohol))
print(word_alcohol)
print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    


In [2]:
vector = numpy.array([5,10,15,20])
vector[0:3]

array([ 5, 10, 15])

In [3]:
print(vector[0:3])

[ 5 10 15]


In [5]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(matrix[:,1])

[10 25 40]


In [6]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [12]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
second_column_25 = (matrix[:,1] == 25 )
print (second_column_25)
print(matrix[second_column_25,:])

[False  True False]
[[20 25 30]]


In [15]:
vector = numpy.array([5,10,15,20])
equal = (vector == 10) & (vector == 5 )
print (equal)


[False False False False]


In [16]:
vector = numpy.array([5,10,15,20])
equal = (vector == 10) | (vector == 5 )
print (equal)

[ True  True False False]


In [17]:
vector = numpy.array(["1","2","3"])
print (vector.dtype)

<U1


In [18]:
print (vector)

['1' '2' '3']


In [19]:
vector = vector.astype(float)
print (vector.dtype)
print(vector)

float64
[1. 2. 3.]


In [1]:
import numpy as np


NameError: name 'numpy' is not defined

In [3]:
import numpy

In [4]:
word_alcohol = numpy.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str)

In [5]:
word_alcohol = numpy.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str,skip_header=1)

In [6]:
print(word_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [7]:
g_other_1986 = word_alcohol[1,4]
print(g_other_1986)

0.5


In [8]:
vecetor = numpy.array([5,10,15,20])
print(vecetor)

[ 5 10 15 20]


In [9]:
print(vecetor[0:3])

[ 5 10 15]


In [10]:
equal_to_ten = (vecetor == 10 )
print(equal_to_ten)

[False  True False False]


In [11]:
print(vecetor[equal_to_ten])

[10]


In [12]:
vector = numpy.array([5,10,15,20])
vector.min()

5

In [1]:
import numpy as np

In [2]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
a = np.arange(15).reshape(3,5)

In [5]:
5

5

In [6]:
a = np.arange(15).reshape(3,5)

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [11]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [12]:
np.arange(1,50,10)

array([ 1, 11, 21, 31, 41])

In [13]:
np.arange(18).reshape(4,3)

ValueError: cannot reshape array of size 18 into shape (4,3)

In [14]:
np.arange(18).reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
np.random.random((2,3))

array([[0.09925127, 0.45147664, 0.03336005],
       [0.37039719, 0.7878174 , 0.28686029]])

In [16]:
from numpy import pi 

In [17]:
np.linspace(0,0.2*pi,100)

array([0.        , 0.00634665, 0.0126933 , 0.01903996, 0.02538661,
       0.03173326, 0.03807991, 0.04442656, 0.05077321, 0.05711987,
       0.06346652, 0.06981317, 0.07615982, 0.08250647, 0.08885313,
       0.09519978, 0.10154643, 0.10789308, 0.11423973, 0.12058638,
       0.12693304, 0.13327969, 0.13962634, 0.14597299, 0.15231964,
       0.1586663 , 0.16501295, 0.1713596 , 0.17770625, 0.1840529 ,
       0.19039955, 0.19674621, 0.20309286, 0.20943951, 0.21578616,
       0.22213281, 0.22847947, 0.23482612, 0.24117277, 0.24751942,
       0.25386607, 0.26021272, 0.26655938, 0.27290603, 0.27925268,
       0.28559933, 0.29194598, 0.29829264, 0.30463929, 0.31098594,
       0.31733259, 0.32367924, 0.33002589, 0.33637255, 0.3427192 ,
       0.34906585, 0.3554125 , 0.36175915, 0.36810581, 0.37445246,
       0.38079911, 0.38714576, 0.39349241, 0.39983907, 0.40618572,
       0.41253237, 0.41887902, 0.42522567, 0.43157232, 0.43791898,
       0.44426563, 0.45061228, 0.45695893, 0.46330558, 0.46965

In [18]:
np.sin(np.linspace(0,2*pi,100))

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [22]:
a = np.array([20,30,40,50])
b = np.arange(4)
a
b

array([0, 1, 2, 3])

In [20]:
a

array([20, 30, 40, 50])

In [21]:
b

NameError: name 'b' is not defined

In [23]:
b

array([0, 1, 2, 3])

In [24]:
c = a - b 

In [25]:
c

array([20, 29, 38, 47])

In [26]:
B = np.arange(3)
B

array([0, 1, 2])

In [27]:
print(np.exp(B))

[1.         2.71828183 7.3890561 ]


In [28]:
print(np.sqrt(B))

[0.         1.         1.41421356]


In [29]:
a = np.floor(10*np.random.random((3,4)))
a

array([[3., 0., 8., 3.],
       [1., 7., 8., 1.],
       [7., 2., 2., 0.]])

In [30]:
b = np.arange(6)

In [31]:
b

array([0, 1, 2, 3, 4, 5])

In [32]:
b.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
b.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
a.revel()

AttributeError: 'numpy.ndarray' object has no attribute 'revel'

In [35]:
print(a.ravel())

[3. 0. 8. 3. 1. 7. 8. 1. 7. 2. 2. 0.]


In [36]:
a

array([[3., 0., 8., 3.],
       [1., 7., 8., 1.],
       [7., 2., 2., 0.]])

In [37]:
a.shape

(3, 4)

In [38]:
a.shape(6,2)

TypeError: 'tuple' object is not callable

In [39]:
a.shape = (6,2)

In [40]:
a

array([[3., 0.],
       [8., 3.],
       [1., 7.],
       [8., 1.],
       [7., 2.],
       [2., 0.]])

In [41]:
print(a.T)

[[3. 8. 1. 8. 7. 2.]
 [0. 3. 7. 1. 2. 0.]]


In [42]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))



In [43]:
a

array([[8., 9.],
       [7., 6.]])

In [44]:
b

array([[3., 7.],
       [7., 4.]])

In [45]:
print(np.hstack((a,b)))

[[8. 9. 3. 7.]
 [7. 6. 7. 4.]]
